version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-duxus
    environment:
      POSTGRES_DB: duxus
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: duxus-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  pgdata:
